<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <LangVersion>8.0</LangVersion>
    <RootNamespace>GuestGate.Desktop</RootNamespace>
    <Company>IBAApps</Company>
    <Authors>Ammar </Authors>
    <PackageIcon>GuestGate.png</PackageIcon>
    <ApplicationIcon>GuestGate.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="GuestGate.ico" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\..\..\Desktop\GuestGate.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.7" />
    <PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="4.10.0" PrivateAssets="all" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Enrichers.Process" Version="3.0.0" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="ResultsForm - Copy.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>
</Project>
